name: Release
on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Install semantic-release extra plugins
        run: yarn add @semantic-release/changelog @semantic-release/git -D
      - name: Prettier
        run: yarn run prettier:fix
      - name: Lint
        run: yarn run lint:fix
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn run build
      - name: Docs
        run: yarn run docs
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
